name:                cad-talk
version:             0.1.0.0
github:              "githubuser/cad-talk"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2025 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/cad-talk#readme>


default-extensions: OverloadedStrings

dependencies:
- base >= 4.7 && < 5
- text
- containers
- lens
- linear
- doctemplates
- pandoc
- pandoc-types
- megaparsec
- JuicyPixels
- svg-tree
- xml
- fsnotify
- optparse-applicative
- split
- qrcode-core
- vector
- directory
- process

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  cad-talk-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cad-talk
